#!/usr/bin/env bash
set -ueo pipefail
scriptDir=$(cd $(dirname $0); pwd)
echo $scriptDir
scala_version=2.12

java -Xmx1g -Xss2M \
     -cp $scriptDir/ducttape.jar \
     -Dfile.encoding="UTF-8" \
     Ducttape "$@"
